#!/bin/bash
gp_version=1.0
gammapy download notebooks --out notebooks/
mv notebooks/$gp_version tmp
mkdir notebooks/$gp_version
mv tmp notebooks/$gp_version/tutorials
gammapy download datasets --out datasets/
