#!/bin/bash
gammapy download notebooks --out notebooks/
mv notebooks/dev tmp
mkdir mv notebooks/dev
mv tmp mv notebooks/dev/tutorials
gammapy download datasets --out datasets/
export GAMMAPY_DATA=$PWD/datasets/dev
