# Conda environment for Gammapy version 2.0rc1
# Install:    conda env create -f gammapy-2.0rc1-environment.yml
# Activate:   conda activate gammapy-2.0rc1
# Deactivate: conda deactivate

name: gammapy-2.0rc1

channels:
  - conda-forge
  - https://cxc.cfa.harvard.edu/conda/sherpa

variables:
  PYTHONNOUSERSITE: "1"

dependencies:
  - python=3.12
  - ipython=8.27
  - cython
  - jupyter
  - jupyterlab=4.2
  - pyyaml=6.0
  - click=8.2
  - numpy=2.1
  - scipy=1.16
  - pandas=2.2
  - matplotlib=3.9
  - astropy=7.1
  - regions=0.10
  - iminuit=2.31
  - healpy=1.18
  - naima=0.10
  - pydantic=2.11
  - corner=2.2
  - pip
  - requests
  - tqdm
  - pip:
    - gammapy==2.0rc1
    - ray[default]==2.48
